spring:
  datasource:
    url: jdbc:mysql://10.38.2.12:30306/deployer?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

helm:
  charts:
    dir: file:./data/charts

clusters:
  dir: file:./data/clusters

apps:
  dir: file:./data/apps
debug: true
