server:
  port: 8080

spring:
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://10.38.2.12:30306/deployer?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: com.github.caijh.framework.orm.mysql.CustomMySqlDialect

helm:
  charts:
    dir: classpath:static/charts

clusters:
  dir: classpath:static/clusters

apps:
  dir: classpath:static/apps
debug: true
